version: "3"

services:
  app:
    build: .
    command: "rails server -p 3010 -b '0.0.0.0'"
    volumes:
      - .:/usr/src/app
    ports:
      - "3010:3010"
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    image: postgres
